export {
  ErrorDelServidor,
  NoEncontrado,
  NovelaOcupada,
  Rechazada,
  SinRespuesta,
  tipoDeError,
  type TipoDeError,
} from './errores'
export {
  leerFicha,
  pedirCambio,
  type AcuseDeCambio,
  type CuerpoDeCambio,
  type FichaConHistorial,
  type VersionPublicada,
} from './novelas'
export {
  leerCapitulo,
  leerDiferencias,
  leerFichas,
  leerVersion,
  urlDelPdf,
  type CapituloDelManifiesto,
  type Diferencias,
  type FichaEscenario,
  type FichaPersonaje,
  type Fichas,
  type Licencia,
  type Paratexto,
  type TextoDeCapitulo,
  type VersionDeNovela,
} from './versiones'
export {
  leerGate,
  leerPanel,
  leerRegistro,
  leerTaller,
  type CapituloDelPanel,
  type Conversacion,
  type EstadoDeFase,
  type EstadoDeNovela,
  type FaseDelPanel,
  type FilaEditable,
  type GateDeNovela,
  type GatePendiente,
  type Panel,
  type RevisionDeLaTrama,
  type Suceso,
  type TarjetaNovela,
} from './seguimiento'
export {
  leerIntento,
  leerSalida,
  type Ejecucion,
  type Hecho,
  type SalidaDeFase,
  type SalidaEncargo,
  type SalidaEscritura,
  type SalidaInvestigacion,
  type SalidaPublicacion,
  type SalidaRegeneracion,
  type SalidaTrama,
  type TextoDeIntento,
} from './fases'
export {
  continuar,
  decidir,
  desbloquear,
  descartarHecho,
  editarFila,
  encargar,
  leerEjemplos,
  reintentar,
  validarEncargo,
  type CuerpoDeEdicion,
  type Ejemplo,
  type Encargo,
  type ErrorDeCampo,
  type Hecha,
  type Lanzada,
  type ModoDeInvestigacion,
  type Validacion,
} from './operacion'
